services:
  web-node:
    image: "${GC_WEB_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-web-node"
    user: "1000:1000"
    environment:
      REACT_APP_GC_DECOUPLED: "true"
      REACT_APP_NODE_ENV: "production"
      REACT_APP_GLUU_SSO: "disabled"
      REACT_APP_MATOMO_LINK: "http://matomo"
      REACT_APP_DATA_CATALOG_LINK: "http://data-catalog.local:8443"
      REACT_APP_CLASSIFICATION_BANNER: "UNCLASSIFIED"
      REACT_APP_CLASSIFICATION_BANNER_COLOR: "GREEN"
      REACT_APP_SUPPORT_HREF: "https://support.local/plugins/servlet/desk/portal/5/create/113"
      REACT_APP_WIKI_HREF: "http://wiki.local"
      GAMECHANGER_DEMO_DEPLOYMENT: "true"
      GAMECHANGER_DEMO_USER: "007"
      GAMECHANGER_DISABLE_STATS_API: "true"
      S3_REGION: "us-east-1"
      S3_IS_MINIO: "true"
      S3_ACCESS_KEY: "dev-access-key"
      S3_SECRET_KEY: "dev-secret-key"
      S3_ENDPOINT: "http://s3-server:9000"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - redis
      - postgres
    ports:
      - "8990:8990"
      - "8443:8443"
    networks:
      - app-net
    entrypoint:
      - '/bin/bash'
      - '-ec'
    command:
      - |
        cd /opt/app-root/src/backend
        node index.js

  web-react:
    image: "${GC_WEB_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-web-react"
    user: "1000:1000"
    environment:
      REACT_APP_GC_DECOUPLED: "true"
      REACT_APP_NODE_ENV: "production"
      REACT_APP_GLUU_SSO: "disabled"
      REACT_APP_MATOMO_LINK: "http://matomo"
      REACT_APP_DATA_CATALOG_LINK: "http://data-catalog.local:8443"
      REACT_APP_CLASSIFICATION_BANNER: "UNCLASSIFIED"
      REACT_APP_CLASSIFICATION_BANNER_COLOR: "GREEN"
      REACT_APP_SUPPORT_HREF: "https://support.local/plugins/servlet/desk/portal/5/create/113"
      REACT_APP_WIKI_HREF: "http://wiki.local"
      GAMECHANGER_DEMO_DEPLOYMENT: "true"
      GAMECHANGER_DEMO_USER: "007"
      GAMECHANGER_DISABLE_STATS_API: "true"
      S3_REGION: "us-east-1"
      S3_IS_MINIO: "true"
      S3_ACCESS_KEY: "dev-access-key"
      S3_SECRET_KEY: "dev-secret-key"
      S3_ENDPOINT: "http://s3-server:9000"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-net
    entrypoint:
      - '/bin/bash'
      - '-ec'
    command:
      - |
        cd /opt/app-root/src/frontend
        npm run start

  ml-api:
    image: "${GC_ML_API_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-ml-api"
    user: "1001:1001"
    depends_on:
      - redis
    environment:
      ENV_TYPE: DEVLOCAL
      DOWNLOAD_DEP: "false"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    volumes:
      - "ml-api-data:/opt/app-root/src/gamechangerml/models"
    networks:
      - app-net
    command:
      - |
        tail -F anything

  redis:
    image: "${GC_REDIS_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-redis"
    user: root
    ports:
      - "6379:6379"
    volumes:
      - "redis-etc:/usr/local/etc"
      - "redis-data:/data"
    networks:
      - app-net
    sysctls:
      - net.core.somaxconn=1024

  elasticsearch:
    image: "${GC_ELASTICSEARCH_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-elasticsearch"
    user: root
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
    networks:
      - app-net

  kibana:
    image: "${GC_KIBANA_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-kibana"
    user: root
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - app-net

  s3-server:
    image: "${GC_S3_SERVER_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-s3-server"
    user: root
    ports:
      - "9000:9000"
    volumes:
      - "s3-data:/s3-data"
    environment: 
      - "MINIO_ACCESS_KEY=dev-access-key"
      - "MINIO_SECRET_KEY=dev-secret-key"
      - "MINIO_REGION_NAME=us-east-1"
    command:
      - server
      - /s3-data
    networks:
      - app-net

  postgres:
    image: "${GC_POSTGRES_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-postgres"
    user: root
    ports:
      - "5432:5432"
    volumes:
#      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "pg-data:/pg-data"
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=postgres"
      - "PGDATA=/pg-data"
#      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - app-net

  data-pipelines:
    image: "${GC_DATA_PIPELINES_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME:-gc}-data-pipelines"
    command:
      - "true"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-net

  matomo:
    image: matomo:4.3
    container_name: matomo
    environment: 
      - MATOMO_DATABASE_HOST=mysql
      - MATOMO_DATABASE_USERNAME=root
      - MATOMO_DATABASE_PASSWORD=password
      - MATOMO_DATABASE_DBNAME=matomo
    depends_on: 
      - mysql
    ports:
      - 80:80
    volumes:
      - matomo:/var/www/html
    networks:
      - app-net

volumes:
    mysql:
    matomo: 
